name: Build Firmware

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        board: [pico, pico2]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Install toolchain
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake build-essential python3 gcc-arm-none-eabi libnewlib-arm-none-eabi
      - name: Build ${{ matrix.board }}
        run: ./build.sh ${{ matrix.board }}
      - name: Upload UF2
        uses: actions/upload-artifact@v4
        with:
          name: uart-bridge-${{ matrix.board }}
          path: build/${{ matrix.board }}/uart_bridge.uf2
